version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws sts get-caller-identity --query Account --output text > account.txt
      - export AWS_ACCOUNT_ID=$(cat account.txt)
      - export AWS_DEFAULT_REGION=us-east-1
      - echo AWS Account ID $AWS_ACCOUNT_ID
      - echo AWS Region $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION > password.txt
      - cat password.txt | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logged in to Amazon ECR
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG ./backend
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Deploying to App Runner...
      - |
        aws apprunner create-service --cli-input-json '{
          "ServiceName": "aws-ready-app",
          "SourceConfiguration": {
            "ImageRepository": {
              "ImageIdentifier": "'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_DEFAULT_REGION'.amazonaws.com/'$IMAGE_REPO_NAME':'$IMAGE_TAG'",
              "ImageConfiguration": {
                "Port": "8080",
                "RuntimeEnvironmentVariables": {
                  "FLASK_APP": "app.py",
                  "ANTHROPIC_API_KEY": "{{resolve:ssm:/app/ANTHROPIC_API_KEY:1}}",
                  "HERACLES_S3_BUCKET": "{{resolve:ssm:/app/HERACLES_S3_BUCKET:1}}",
                  "HERACLES_S3_PREFIX": "{{resolve:ssm:/app/HERACLES_S3_PREFIX:1}}",
                  "AWS_DEFAULT_REGION": "{{resolve:ssm:/app/AWS_DEFAULT_REGION:1}}"
                }
              },
              "ImageRepositoryType": "ECR"
            },
            "AutoDeploymentsEnabled": true
          },
          "InstanceConfiguration": {
            "Cpu": "1 vCPU",
            "Memory": "2 GB"
          }
        }'
      - echo Deployment to App Runner completed